changeLogFile: wc_db_master_changelog.xml
driver: org.postgresql.Driver
classpath:../../common/jdbc_drivers/postgresql-42.7.11.jar
logLevel: info
defaultSchemaName: wc01
liquibaseSchemaName: wc01
databaseChangeLogTableName: wcdbmasterchangelog
databaseChangeLogLockTableName: wcdbmasterchangeloglock