-- liquibase formatted sql


--changeset jnolte:2020521_create_game_files
INSERT INTO game_profile (app_file_id, title, description, genre_id)
VALUES (1, 'Gold Rush', 'The text is very blurry if it is not Fullscreen, so I highly recommend Fullscreen.
For the gamejam it is western because the gold rush in California is one of the leading contributions to starting the western era.', 9),
(2, 'IceCave', 'Controls:
WASD to move
Spacebar to push boxes
Click on water to freeze/unfreeze it (3 frozen things max)
Escape to close the game

Collect all 4 snowflakes to enter the Ice Cave!

Made for the 2024 Winter Texas State GDS Game Jam

Credits:
Spopa - Programming
BigManJD - Programming & Art

Thanks for playing!', 4),
(3, 'PlanetGame', 'The galaxy is vast an full of wonders.
In this game, you take on the role of Houston - a dragonborn astronaut who dreams of exploring the galaxy, every wonder and every horror.

Use A and D to move left and right. SPACE to jump, and SHIFT activates your breth weapon. This launches you in the opposite direction you aim it in.

There are gravity fields and planets that change what direction down is. Remember in space, there is no such thing as down.

Note: This is a Tech Demo - just to showcase the gravity mechanics. Hopefully, I can develop it into a full game.', 3),
(4, 'starfrontier', 'Starfrontier is a large-scale science fiction exploration game focused on survival, diplomacy, and interstellar warfare. Players begin as low-ranking navigators aboard a damaged colony vessel drifting near the edge of charted space. With resources running low and rival factions competing for control, every decision shapes the fate of the surviving crew. The game combines open-world exploration with tactical ship combat, allowing players to customize engines, shield systems, crew assignments, and experimental weapons scavenged from abandoned stations. Beyond combat, Starfrontier emphasizes discovery. Ancient alien ruins contain fragmented lore describing civilizations that vanished thousands of years before humanity arrived. As players travel across asteroid fields, mining colonies, frozen moons, and unstable nebula sectors, they uncover hidden technologies capable of changing the balance of power. Dynamic faction systems allow alliances with traders, mercenaries, scientists, or outlaw raiders, each offering unique quests and story outcomes. Multiplayer expeditions let crews work together to explore dangerous anomalies or compete for rare resources hidden deep within uncharted sectors. The soundtrack mixes atmospheric synth themes with tense combat audio to create a cinematic space adventure. Starfrontier rewards strategic thinking, curiosity, and long-term planning while maintaining fast-paced action during fleet encounters.', 8),
(5, 'dungeonquest', 'DungeonQuest is a fantasy action RPG inspired by classic dungeon crawlers and cooperative tabletop adventures. Players enter the kingdom of Valeron, a land overrun by cursed creatures after an ancient magical seal beneath the capital city shattered during a forbidden ritual. The game features procedurally generated dungeons filled with traps, treasure chambers, hidden passages, and powerful bosses guarding legendary equipment. Players choose between several classes including warrior, ranger, alchemist, shadow rogue, and elemental mage, each with customizable skill trees and equipment specializations. Combat focuses on timing, positioning, and teamwork, rewarding players who combine abilities effectively. Crafting systems allow the forging of enchanted armor, brewing of rare potions, and creation of magical relics discovered deep underground. DungeonQuest also includes town-building mechanics where rescued villagers expand shops, unlock training halls, and reveal new storylines. Seasonal events introduce rotating dungeons with unique environmental hazards such as collapsing ruins, cursed forests, and lava caverns. The visual style combines detailed pixel-inspired art with modern lighting effects, creating a nostalgic but polished fantasy atmosphere. Every expedition offers new challenges, encouraging replayability and experimentation while uncovering the dark secrets buried beneath Valeron.', 7),
(6, 'cyberstrike', 'CyberStrike is a futuristic tactical shooter set in the neon-lit megacity of Vireon, where corporations secretly wage war through cybernetic mercenaries and AI-controlled armies. Players take control of customizable operatives equipped with advanced implants, hacking tools, and experimental weapon systems. Missions range from stealth infiltrations inside corporate skyscrapers to large-scale firefights across crowded industrial districts and underground data vaults. The game blends fast gunplay with strategic hacking mechanics, allowing players to disable enemy drones, manipulate security systems, or overload power grids during combat. Multiplayer modes feature squad-based objectives emphasizing teamwork and synchronized abilities, while the single-player campaign explores themes of surveillance, artificial intelligence, and corporate corruption. Character progression unlocks new cybernetic upgrades that modify movement speed, targeting systems, cloaking technology, and defensive capabilities. Dynamic weather systems and day-night cycles influence enemy behavior and mission strategies. CyberStrike also supports user-created maps and community events where factions compete for control over sectors of the city. The soundtrack combines electronic synthwave music with industrial sound design to reinforce the dystopian atmosphere. Every match encourages adaptability, precision, and tactical creativity as players navigate a dangerous world ruled by information and technology.', 9),
(7, 'pixelracer', 'PixelRacer is an arcade-style racing game inspired by retro driving classics and modern competitive speedrunning games. Players compete across vibrant pixel-art environments including neon city streets, desert highways, mountain passes, snow-covered villages, and futuristic hover tracks suspended above massive skylines. The game emphasizes fast reflexes and aggressive maneuvering, rewarding players who drift around corners, chain near misses, and maintain high-speed combos for score multipliers. Vehicles range from vintage muscle cars and rally trucks to experimental anti-gravity racers, each featuring distinct handling and upgrade paths. Career mode follows an underground racing league where players climb through regional tournaments to challenge elite champions across increasingly difficult circuits. Multiplayer supports local split-screen and online competitions with ranked ladders, ghost replay sharing, and community tournaments. Track hazards include collapsing bridges, sandstorms, ice patches, traffic congestion, and dynamic weather changes that alter visibility and traction. PixelRacer features a customizable soundtrack system and garage editor where players can personalize vehicle colors, decals, wheels, and performance tuning. Hidden shortcuts and collectible parts encourage repeated playthroughs to master every route. Despite its retro-inspired appearance, the game includes modern physics systems and responsive controls designed for both casual players and highly competitive racers.', 6),
(8, 'voidexpanse', 'VoidExpanse is a survival-focused space exploration game set inside a collapsing region of deep space known as the Expanse Rift. Entire fleets have disappeared within the Rift after strange gravitational anomalies began distorting navigation systems and communication signals. Players pilot customizable ships while managing fuel, oxygen, food supplies, crew morale, and structural damage during long expeditions across dangerous sectors. The game combines sandbox freedom with narrative-driven mysteries surrounding ancient entities hidden within the void. Planets and stations are procedurally generated, creating unique encounters involving pirate ambushes, abandoned research facilities, and unstable wormholes. Players may trade resources, salvage derelict vessels, or establish outposts to support future exploration routes. Combat emphasizes positioning and energy management, with ships requiring careful balancing of shields, engines, and weapon systems during battles. Alien technology recovered from forgotten ruins grants powerful upgrades but often introduces unpredictable side effects. The game’s atmosphere is heavily influenced by isolation and uncertainty, supported by minimalist sound design and haunting environmental effects. Multiplayer survival servers allow alliances and betrayals between crews competing for scarce resources. VoidExpanse encourages patience, planning, and curiosity while slowly revealing the terrifying truth hidden within the Rift.', 10),
(9, 'mechawars', 'MechaWars is a large-scale mechanized warfare game where players pilot customizable combat machines across devastated battlefields shaped by decades of global conflict. Nations have collapsed, leaving independent military factions and private corporations fighting over rare energy resources capable of powering advanced mech technology. Players can choose lightweight reconnaissance mechs, balanced assault frames, or heavily armored siege units designed for frontline warfare. Every mech can be modified with interchangeable weapons, mobility systems, armor plating, and experimental modules that dramatically alter battlefield performance. Missions include city defense operations, convoy escorts, sabotage raids, and massive faction wars involving dozens of AI-controlled units. Terrain destruction plays a major role, allowing buildings, bridges, and fortifications to collapse dynamically during combat. The campaign follows multiple perspectives across the conflict, exploring the moral consequences of endless mechanized warfare. Multiplayer features ranked team battles and cooperative operations against rogue AI armies. Resource management systems require players to maintain repair facilities and supply chains between missions. The visual presentation combines gritty industrial aesthetics with cinematic explosions and detailed mechanical animations. MechaWars rewards strategic positioning, teamwork, and careful customization while delivering intense action on a massive scale.', 9),
(10, 'arcanelands', 'ArcaneLands is a fantasy adventure RPG set in a world fractured by magical storms that reshaped entire kingdoms. Players assume the role of a wandering mage hunter tasked with investigating the sudden appearance of corrupted creatures and unstable magical zones spreading across the continent. The game combines open-world exploration, tactical combat, and faction diplomacy as players travel between ruined castles, enchanted forests, underground temples, and floating islands suspended by ancient magic. Combat revolves around combining elemental abilities, enchanted weapons, and environmental interactions to defeat powerful enemies. Players can freeze rivers to cross dangerous terrain, ignite oil traps during battles, or summon storms that alter visibility and enemy movement. A deep progression system allows mastery over schools of magic including fire, frost, shadow, light, and arcane manipulation. Throughout the story, players encounter rival factions ranging from royal knights and rogue sorcerers to scholars seeking forbidden knowledge. Decisions made during quests influence political alliances, settlement development, and access to rare abilities. ArcaneLands features a dynamic weather system where magical storms create unpredictable world events and hidden dungeons. Crafting systems allow players to forge enchanted armor, brew alchemical potions, and inscribe powerful runes onto equipment. Multiplayer expedition modes let groups tackle dangerous raids against corrupted titans and legendary beasts hidden within ancient ruins. The visual style combines detailed fantasy landscapes with glowing magical effects and atmospheric orchestral music that reinforces the sense of mystery and adventure.', 8),
(11, 'shadowrealm', 'ShadowRealm is a dark fantasy action game focused on exploration, survival, and psychological horror within a cursed dimension slowly consuming reality. Players awaken inside a forgotten fortress with no memory of how they arrived, surrounded by shifting corridors and creatures born from fear itself. The game world constantly changes based on player actions, creating unpredictable layouts, hidden encounters, and environmental storytelling that rewards careful observation. Combat emphasizes resource management and timing rather than pure aggression, forcing players to balance melee combat, ranged weapons, traps, and rare magical artifacts. Throughout the campaign, players uncover fragments of ancient history describing the collapse of a once-powerful civilization that attempted to control forbidden energies hidden beneath the world. Multiple endings depend on the alliances formed with surviving factions and the choices made while exploring dangerous regions including abandoned catacombs, haunted villages, corrupted forests, and underground sanctuaries. ShadowRealm also features sanity mechanics where exposure to supernatural forces distorts visuals, alters enemy behavior, and unlocks hidden dialogue. Cooperative multiplayer allows small groups to venture into procedurally generated nightmare zones filled with elite enemies and rare rewards. The soundtrack relies heavily on ambient audio, distant whispers, and minimal orchestration to build tension throughout the experience. ShadowRealm is designed to immerse players in a constantly unsettling world where survival depends on caution, curiosity, and the willingness to confront terrifying truths.', 10),
(12, 'neonfighters', 'NeonFighters is a competitive arena combat game set in a futuristic entertainment district where elite pilots battle inside holographic stadiums broadcast to millions of viewers across the galaxy. Players control highly agile combat frames equipped with customizable energy weapons, mobility boosters, defensive barriers, and unique special abilities. Matches focus on speed, teamwork, and positioning, combining fast-paced shooting mechanics with traversal systems that allow wall running, aerial dashes, grappling hooks, and environmental interactions. Multiple game modes include elimination tournaments, objective control, free-for-all events, and ranked championship circuits. The story mode follows a rookie fighter entering the professional league after uncovering evidence of corruption behind the tournament organizers and illegal experimentation on combat pilots. Progression systems unlock cosmetic upgrades, combat modules, and sponsor contracts that provide additional challenges and rewards. Arenas range from neon-lit rooftops and industrial factories to zero-gravity chambers and holographic simulations capable of dynamically changing terrain mid-match. NeonFighters also includes replay tools, spectator modes, and community tournaments designed for competitive events. The visual style emphasizes bright colors, stylized effects, and high-energy electronic music inspired by cyberpunk aesthetics. Every battle encourages aggressive movement, quick decision making, and mastery of advanced mobility mechanics.', 7),
(13, 'crypticforest', 'CrypticForest is a narrative-driven survival mystery game set within a remote woodland region abandoned after a series of unexplained disappearances decades earlier. Players arrive as independent investigators searching for a missing documentary crew that vanished while researching local legends surrounding the forest. Exploration plays a major role as players navigate dense wilderness, abandoned cabins, hidden bunkers, and forgotten research sites while collecting clues and piecing together fragmented stories left behind by previous visitors. The forest itself behaves strangely, with shifting paths, unnatural weather patterns, and distorted sounds that create constant uncertainty. Players must manage food, warmth, flashlight batteries, and mental stability while avoiding hostile wildlife and supernatural entities stalking the environment at night. Puzzle-solving mechanics involve deciphering journals, repairing old communication systems, and uncovering secret underground networks hidden beneath the trees. The story gradually reveals experiments conducted by a private organization attempting to exploit strange anomalies discovered deep within the region. CrypticForest uses advanced environmental audio and dynamic lighting to create immersion and tension without relying heavily on direct combat. Multiplayer cooperative investigation modes allow players to search together for hidden evidence and survive dangerous expeditions into the heart of the forest. The game blends psychological horror, exploration, and survival mechanics into an atmospheric experience focused on mystery and discovery.', 9);
