--liquibase formatted sql


--changeset jnolte:2020521_create_users_profiles
INSERT INTO app_user_profile (app_user_id, display_name, user_bio)
VALUES 	( 1, 'Jaeger Nolte', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 2, 'Jared Wood', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 3, 'Kaden Misenheimer', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 4, 'Crom', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 5, 'Garf', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 6, 'Spopa', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 7, null, 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 8, null, 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 9, null, 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 10, null, 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 11, null, 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 12, null, 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 13, 'Peturabo', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 14, 'Mortarion', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 15, 'Angron', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 16, 'Sanguinius', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 17, 'Jagatai Khan', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 18, 'Garviel Loken', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 19, 'Magnus, The Red', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 20, 'Nathaniel Garo', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 21, 'Erobus', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 22, 'Argal Tal', 'Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi.'),
( 23, 'Musashi', 'Billy Bob Johnson at your service.'),
(24, 'VoltageVagrant', 'Night owl, coffee addict, and part-time game modder. Usually found tinkering with side projects or exploring random corners of the internet.'),
(25, 'EmmaSkylark', 'Book collector and amateur photographer who loves rainy weather, indie music, and late-night coding sessions.'),
(26, 'HexaNova', 'Digital artist obsessed with sci-fi worlds, neon lights, and experimental playlists. Always creating something strange.'),
(27, 'LiamOnWheels', 'Cyclist, traveler, and burger enthusiast. I spend weekends chasing trails and weekdays pretending to be productive.'),
(28, 'PixelHarbor', 'Retro gaming fan with a weakness for old RPGs and pixel art. Probably replaying something from the 90s right now.'),
(29, 'SophiaBloom', 'Tea drinker, cat lover, and aspiring novelist. I enjoy cozy games, cloudy mornings, and writing unfinished stories.'),
(30, 'WolfByte', 'Cybersecurity student who enjoys breaking things just to learn how they work. Mostly harmless.'),
(31, 'CalebNorth', 'Musician by passion, developer by trade. Usually balancing between guitar practice and debugging impossible errors.'),
(32, 'LunaCascade', 'Dreamer with a fascination for astronomy, digital design, and synthwave playlists that last for hours.'),
(33, 'OliveJuniper', 'Plant collector and café explorer. I document tiny moments and try to make everyday life feel cinematic.'),
(34, 'EchoNomad', 'Traveler of virtual worlds and real cities. Big fan of survival games, ramen spots, and spontaneous road trips.'),
(35, 'NoahEvergreen', 'Runner, podcast addict, and hobby photographer. Always searching for the perfect sunset shot.'),
(36, 'MantisPrime', 'Tech enthusiast who spends too much time customizing keyboards and not enough time sleeping.'),
(37, 'AverySkies', 'Enjoys painting, indie films, and wandering bookstores for hours without buying anything.'),
(38, 'SolarFlareX', 'Space documentaries, competitive games, and energy drinks fuel most of my decisions.'),
(39, 'MiaRivera', 'Coffee-powered creative who loves journaling, quiet cafés, and finding hidden music artists online.'),
(40, 'SyntaxGhost', 'Backend developer with an unhealthy obsession for automation and terminal themes.'),
(41, 'EthanForge', 'Gym regular, sneaker collector, and casual gamer trying to beat my backlog one game at a time.'),
(42, 'VelvetOrbit', 'Fashion enthusiast with a soft spot for futuristic aesthetics, vinyl records, and city nightlife.'),
(43, 'ChloeAurora', 'Lover of watercolor art, hiking trails, and overly dramatic playlists that feel like movie soundtracks.'),
(44, 'RavenCipher', 'Late-night strategist and online multiplayer veteran. Usually online when everyone else is asleep.'),
(45, 'JacksonVale', 'Mechanical keyboard nerd and aspiring content creator who spends too much money on desk setups.'),
(46, 'PixelShade', 'Animation fan, meme archivist, and collector of random internet trivia nobody asked for.'),
(47, 'HarperFrost', 'Minimalist lifestyle enthusiast with a love for clean aesthetics, quiet mornings, and tea.'),
(48, 'NovaFlicker', 'Sci-fi reader and casual streamer who enjoys chaotic sandbox games and midnight snacks.'),
(49, 'LucasStone', 'Outdoor explorer balancing hiking adventures with long gaming marathons at home.'),
(50, 'QuantumShade', 'Physics student fascinated by AI, weird theories, and late-night rabbit holes on the internet.'),
(51, 'EllaWren', 'Creative soul who enjoys sketching, baking, and turning small apartments into cozy spaces.'),
(52, 'CipherNoir', 'Mysterious internet wanderer with too many saved playlists and not enough free storage.'),
(53, 'MasonDrift', 'Skateboarding, photography, and finding hidden food spots around the city keep me busy.'),
(54, 'CrimsonPulse', 'Competitive gamer and tech reviewer who probably owns more headphones than necessary.'),
(55, 'GraceHollow', 'Fantasy novel enthusiast with a love for candlelit evenings and handwritten notes.'),
(56, 'TurboOtter', 'Chaotic energy packed into one human. Loves racing games, spicy food, and loud music.'),
(57, 'BenjiCross', 'Fitness enthusiast trying to stay consistent while juggling work, hobbies, and way too many tabs open.'),
(58, 'StaticVoyager', 'Always experimenting with creative side projects, from music production to tiny game prototypes.'),
(59, 'ZoeWinter', 'Digital illustrator inspired by nature, dreamy aesthetics, and colorful city lights after rain.'),
(60, 'OmegaTrail', 'Adventure seeker who enjoys mountain trips, survival gear, and documenting every journey.'),
(61, 'DanielArc', 'Software engineer who spends free time learning random skills I may never actually use.'),
(62, 'RetroNova', 'Collector of retro consoles, VHS tapes, and nostalgic internet culture from the early 2000s.'),
(63, 'AmeliaVale', 'Soft-spoken artist who enjoys quiet mornings, fantasy worlds, and baking desserts from scratch.'),
(64, 'VoidSignal', 'Sleeps late, codes often, and somehow survives entirely on caffeine and curiosity.'),
(65, 'HenryAsh', 'History buff with a love for strategy games, documentaries, and old architecture.'),
(66, 'LunarBloom', 'Astrology fan who enjoys dreamy aesthetics, photography walks, and collecting crystals.'),
(67, 'ScarletEcho', 'Music lover with a dramatic fashion sense and a playlist for every possible mood.'),
(68, 'ForgePixel', '3D modeling hobbyist and gamer who enjoys building strange worlds just for fun.'),
(69, 'LoganSkye', 'Weekend traveler and amateur filmmaker chasing good lighting and memorable moments.'),
(70, 'BloomCipher', 'Quiet observer with a love for digital art, mystery novels, and rainy day playlists.'),
(71, 'AubreyRune', 'Fantasy gamer and tea enthusiast who enjoys cozy spaces and storytelling adventures.'),
(72, 'StormVector', 'Competitive FPS player, gym regular, and certified overthinker with too many unfinished projects.'),
(73, 'NathanVale', 'Tech-focused creative balancing app ideas, gaming nights, and occasional attempts at cooking.');